rules:
  - id: insecure-output-encoding
    pattern: 'Encode.forHtml'
    message: "Ensure that all user input is properly encoded before returning it."
    severity: WARNING
    languages: [java]

  - id: missing-validation
    pattern: '(@Valid @RequestBody)'
    message: "Ensure all user input is validated."
    severity: WARNING
    languages: [java]
